import type {
  AwardDoc,
  ProjectDoc,
  SiteContentDoc,
  SkillDoc,
} from "@/types/portfolio";

const nowIso = () => new Date().toISOString();

export const defaultSiteContent: SiteContentDoc = {
  singletonKey: "main",
  hero: {
    eyebrow: "Full-Stack & Blockchain Engineer",
    name: "Okoye Emmanuel Obiajulu",
    roles: [
      "Full-Stack Engineer",
      "Stellar / Soroban Contributor",
      "MERN & Next.js Developer",
    ],
    description:
      "I design and ship production-grade web and blockchain products with strong UX, clean architecture, and measurable business outcomes.",
    primaryCtaLabel: "Hire Me",
    primaryCtaUrl: "#contact",
    secondaryCtaLabel: "Download Resume",
    secondaryCtaUrl: "/resume.pdf",
    heroImageFallback: "/images/emmanuel.png",
  },
  about: {
    title: "About",
    summary:
      "Software developer focused on resilient full-stack systems, developer tooling, and Stellar ecosystem products.",
    body:
      "I work across Next.js, TypeScript, Node.js, Python, MongoDB, and smart-contract-oriented workflows. My recent work spans fintech, on-chain products, and developer tooling, with attention to performance, accessibility, and maintainable delivery.",
  },
  socials: {
    github: "https://github.com/Obiajulu-gif",
    linkedin: "https://www.linkedin.com/in/emmanuel-okoye-79a387200/",
    x: "https://x.com/okoye_emma_obi",
    email: "mailto:okoyeemmanuelobiajulu@gmail.com",
    website: "https://okoye-emma-obi.vercel.app",
  },
  contact: {
    email: "okoyeemmanuelobiajulu@gmail.com",
    phone: "+2349069406647",
    location: "Anambra, Nigeria",
  },
  stellarSection: {
    title: "Stellar / Soroban Open Source",
    intro:
      "I actively contribute to Stellar blockchain projects and Soroban tooling.",
    contribution:
      "Contributed to 60+ Stellar ecosystem projects spanning contracts, SDKs, APIs, and developer experience utilities.",
    projectNames: [
      "Soroban-Registry",
      "soroban-debugger",
      "stellar-address-kit",
      "stellarspend-contracts",
      "esustellar",
      "petad-stellar",
      "nftopia-stellar",
    ],
  },
  experience: [
    {
      company: "Chuzol Global Service",
      role: "Software Engineer",
      period: "2025 - Present",
      location: "Remote",
      highlights: [
        "Built and maintained production APIs and full-stack dashboards for internal operations and customer workflows.",
        "Improved delivery consistency by introducing stronger code review and deployment checks.",
        "Collaborated across product and engineering to ship features with measurable user impact.",
      ],
    },
    {
      company: "Netwiver Technologies",
      role: "Frontend Developer",
      period: "2024 - Present",
      location: "Remote",
      highlights: [
        "Developed custom web applications with React and Next.js.",
        "Implemented secure backend integrations and REST APIs.",
        "Delivered responsive and scalable UI systems with Tailwind CSS.",
      ],
    },
    {
      company: "ChainMove",
      role: "MERN Stack Developer",
      period: "2024 - Present",
      location: "Remote",
      highlights: [
        "Contributed to an Uber-like transportation platform powered by blockchain workflows.",
        "Designed and maintained RESTful APIs and authentication flows.",
        "Implemented real-time features for dispatch and rider tracking.",
      ],
    },
    {
      company: "Divine Mercy Computer",
      role: "Manager",
      period: "2017 - 2019",
      location: "Adazi-Nnukwu, Anambra",
      highlights: [
        "Managed day-to-day operations and customer services.",
        "Coordinated typing, printing, and document handling services.",
      ],
    },
  ],
  education: [
    {
      school: "University of Nigeria, Nsukka",
      degree: "B.Sc. Pure and Industrial Chemistry",
      period: "2019 - 2024",
      details: "Faculty Best Programmer of the Year (2024)",
    },
    {
      school: "ALX Africa",
      degree: "Software Engineering Program",
      period: "2023 - 2024",
      details: "Hands-on full-stack engineering training",
    },
    {
      school: "Harvard University",
      degree: "Aspire Leadership Program",
      period: "2024",
      details: "Leadership and impact-focused coursework",
    },
  ],
  resumeHighlights: {
    selectedProjects: [
      "Vault Quest",
      "Prompt Hub",
      "Freelance DAO",
      "ChainMove",
      "Swift",
      "Suibuy",
    ],
    awards: [
      "Best Programmer of the Year (2024)",
      "Winner - Plogging Nigeria Competition",
      "Winner of BlockchainUNN hackathon 4.0 (2025)",
    ],
    coreSkills: [
      "TypeScript",
      "Next.js",
      "Node.js",
      "MongoDB",
      "Soroban",
      "Rust",
    ],
    resumeUrl: "/resume.pdf",
  },
  updatedAt: nowIso(),
};

const defaultSkillsInput: Array<Omit<SkillDoc, "_id" | "updatedAt">> = [
  { name: "TypeScript", category: "Languages", order: 1 },
  { name: "JavaScript", category: "Languages", order: 2 },
  { name: "Python", category: "Languages", order: 3 },
  { name: "Rust", category: "Languages", order: 4 },
  { name: "Solidity", category: "Languages", order: 5 },
  { name: "Next.js", category: "Frontend", order: 6 },
  { name: "React", category: "Frontend", order: 7 },
  { name: "Tailwind CSS", category: "Frontend", order: 8 },
  { name: "Node.js", category: "Backend", order: 9 },
  { name: "Express.js", category: "Backend", order: 10 },
  { name: "Flask", category: "Backend", order: 11 },
  { name: "MongoDB", category: "Data", order: 12 },
  { name: "PostgreSQL", category: "Data", order: 13 },
  { name: "Redis", category: "Data", order: 14 },
  { name: "GSAP", category: "Frontend", order: 15 },
  { name: "GitHub Actions", category: "DevOps", order: 16 },
  { name: "Docker", category: "DevOps", order: 17 },
  { name: "Linux", category: "DevOps", order: 18 },
  { name: "Soroban", category: "Blockchain", order: 19 },
  { name: "Stellar SDK", category: "Blockchain", order: 20 },
];

export const defaultSkills: SkillDoc[] = defaultSkillsInput.map((item) => ({
  ...item,
  updatedAt: nowIso(),
}));

const requiredProjectNames = [
  "ArenaX",
  "TrustUp-API",
  "mindBlock_app",
  "Commitlabs-Contracts",
  "bridgelet-sdk",
  "pacto-p2p",
  "NexaFx-backend",
  "chenpilot",
  "predictify-contracts",
  "PetChain-Contracts",
  "chioma",
  "quest-service",
  "QiuckEx",
  "esustellar",
  "quicklendx-protocol",
  "Remitwise-Contracts",
  "facilpay-api",
  "soroscope",
  "Soter",
  "grainlify",
  "teachLink_mobile",
  "StrellerMinds-Backend",
  "hintents",
  "tip-tune",
  "Soroban-Registry",
  "nftopia-stellar",
  "Callora-Backend",
  "Teye-Contracts",
  "petad-stellar",
  "Commitlabs-Frontend",
  "Uzima-Backend",
  "Credence-Backend",
  "Uzima-Contracts",
  "soroban-debugger",
  "Harvest-Finance",
  "bridgelet-core",
  "stellar-address-kit",
  "OrbitPay",
  "contracts",
  "stellarspend-contracts",
  "flowfi",
  "vestroll",
  "Revora-Backend",
  "zendvo",
  "Valut quest",
  "prompt hub",
  "bluetune",
  "volt",
  "sourcefinder",
  "parabolic exchange",
  "replas",
  "chuzol global",
  "freelance dao",
  "ChainMove",
  "Suibuy",
  "Swift",
  "Zeus Scholarly",
];

export const defaultProjects: ProjectDoc[] = requiredProjectNames.map(
  (name, index) => ({
    name,
    order: index + 1,
    featured: index < 9,
    githubUrl: "",
    description: "",
    tags: [],
    languages: [],
    homepage: "",
    needsRepo: true,
    needsImage: true,
    updatedAt: nowIso(),
  }),
);

export const defaultAwards: AwardDoc[] = [
  {
    title: "Best Programmer of the Year",
    orgOrEvent: "Faculty of Physical Science, University of Nigeria, Nsukka",
    year: 2024,
    placement: "Winner",
    order: 1,
    updatedAt: nowIso(),
  },
  {
    title: "BlockchainUNN Hackathon 3.0",
    orgOrEvent: "BlockchainUNN",
    year: 2024,
    placement: "Second Place",
    order: 2,
    updatedAt: nowIso(),
  },
  {
    title: "SUI on Campus Hackathon",
    orgOrEvent: "SUI on Campus",
    year: 2024,
    placement: "Second Place",
    order: 3,
    updatedAt: nowIso(),
  },
  {
    title: "Nextbridge Africa Hackathon",
    orgOrEvent: "Nextbridge Africa",
    year: 2024,
    placement: "Second Place",
    order: 4,
    updatedAt: nowIso(),
  },
  {
    title: "Rabble Ideathon",
    orgOrEvent: "Rabble",
    year: 2024,
    placement: "Winner",
    order: 5,
    updatedAt: nowIso(),
  },
  {
    title: "Plogging Nigeria Climate Festival Hackathon",
    orgOrEvent: "Plogging Nigeria Climate Festival",
    year: 2025,
    placement: "Winner",
    order: 6,
    updatedAt: nowIso(),
  },
  {
    title: "Enugu Pop City Hackathon",
    orgOrEvent: "Enugu Pop City",
    year: 2025,
    placement: "Winner",
    order: 7,
    updatedAt: nowIso(),
  },
  {
    title: "Anambra Web3 Hackathon",
    orgOrEvent: "Anambra Web3",
    year: 2025,
    placement: "Second Place",
    order: 8,
    updatedAt: nowIso(),
  },
  {
    title: "BlockchainUNN Hackathon 4.0",
    orgOrEvent: "BlockchainUNN",
    year: 2025,
    placement: "Winner",
    order: 9,
    updatedAt: nowIso(),
  },
  {
    title: "Plogging Nigeria Competition",
    orgOrEvent: "Plogging Nigeria",
    year: 2025,
    placement: "Winner",
    order: 10,
    updatedAt: nowIso(),
  },
];
